- hosts: equipos
  gather_facts: yes
  remote_user: "prueba"
  become_method: sudo
  become: true
  # vars:
  #   cv_servicio: "apache2"
  #   cv_accion: "stopped"
  #   cv_servidor: "EUGENE"
  #   service_accion_status: ""
  tasks:
    - name: inicio de bloque
      block:
        - name: Include vars
          ansible.builtin.include_vars: "vars/vars.yml"
            
        - name: Administrar Apache2
          include_tasks: "tasks/apache.yml"
          register: resultado_apache2
          ignore_errors: true
          when: cv_servicio == 'apache2'
        
        - name: Administrar Tomcat
          include_tasks: "tasks/tomcat.yml"
          register: resultado_tomcat
          ignore_errors: true
          when: cv_servicio == 'tomcat'

        - name: Debug resultado
          debug:
            msg: "{{ vars['resultado_' + cv_servicio] }}"

